{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "geektime-ordering-api.serviceAccountName" . }}
  labels:
{{ include "geektime-ordering-api.labels" . | nindent 4 }}
{{- end -}}
