apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: geektime-ordering-api
  namespace: default
  labels:
    app: geektime-ordering-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geektime-ordering-api
    spec:
      containers:
      - name: geektime-ordering-api
        image: "geektime-ordering-api:v1.0.0"
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: "/app/appsettings.json"
            name: appsettings
            subPath: appsettings-v1.0.0.json
        ports:
        - containerPort: 80
        - containerPort: 81
        - containerPort: 443
        env:
          - name: MyEnv
            value: "value from env"
          - name: USE_Forwarded_Headers
            value: "true"
        livenessProbe:
          httpGet:
            path: /live
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          periodSeconds: 3
          successThreshold: 2
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 128Mi
      terminationGracePeriodSeconds: 10
      volumes:
        - name: appsettings
          configMap:
              name: geektime-ordering-api-config
      restartPolicy: Always
--- 

apiVersion: v1
kind: Service
metadata:
  name: geektime-ordering-api
  namespace: default
  labels:
    app: geektime-ordering-api
    HealthChecks: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 81
    targetPort: 81
    protocol: TCP
    name: http2
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: geektime-ordering-api